dei_cafe/urls.py
from django.contrib import admin
from django.urls import path
from reservations import views
from django.contrib.auth.views import LoginView, LogoutView
from reservations.views import LoginView, ReservationView, ReservationCompleteView, ReservationDetailView, ReservationDeleteView, AllReservationsListView, ShopReservationView, ShopReservationCompleteView, ItemListView, ItemCreateView, ItemUpdateView, ItemDeleteView, ShopReservationEditView, ShopReservationDeleteView, CommentManageView

urlpatterns = [
    #ここから顧客用
    path('admin/', admin.site.urls),
    path('', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('menu_user/', views.MenuUserView.as_view(), name="menu_user"),
    path('reserve/list/', views.ReservationListView.as_view(), name="reservation_list"),
    path('reserve/detail/<int:pk>/', ReservationDetailView.as_view(), name="reservation_detail"),
    path('reserve/edit/<int:pk>/', views.ReservationEditView.as_view(), name="reservation_edit"),
    path('reserve/delete/<int:pk>/', views.ReservationDeleteView.as_view(), name="reservation_delete"),
    path('calendar/', views.CalendarView.as_view(), name="calendar"),
    path('calendar/<int:year>/<int:month>/<int:day>/', views.CalendarView.as_view(), name="calendar"),
    path('reserve/<int:year>/<int:month>/<int:day>/<int:hour>/', views.ReservationView.as_view(), name="reserve"),
    path('complete/', views.ReservationCompleteView.as_view(), name="complete"),
    path('register/', views.register, name="register"),
    #ここから店舗用
    path('staff_login/', views.StaffLoginView.as_view(), name="staff_login"),
    path('menu_shop/', views.MenuShopView.as_view(), name="menu_shop"),
    path('menu_shop/list/', views.AllReservationsListView.as_view(), name="menu_shop_list"),
    path('menu_shop/detail/<int:pk>/', views.ShopReservationDetailView.as_view(), name="menu_shop_detail"),
    path('menu_shop/edit/<int:pk>/', views.ShopReservationEditView.as_view(), name="menu_shop_edit"),
    path('menu_shop/delete/<int:pk>/', views.ShopReservationDeleteView.as_view(), name="menu_shop_delete"),
    path('menu_shop/calendar/', views.ShopCalendarView.as_view(), name="menu_shop_calendar"),
    path('menu_shop/calendar/<int:year>/<int:month>/<int:day>/', views.ShopCalendarView.as_view(), name="menu_shop_calendar"),
    path('menu_shop/reserve/<int:year>/<int:month>/<int:day>/<int:hour>/',ShopReservationView.as_view(),name="menu_shop_reserve"),
    path('menu_shop/complete/', views.ShopReservationCompleteView.as_view(), name="menu_shop_complete"),
    path('menu/', views.ItemListView.as_view(), name='menu'),
    path('menu/create/', views.ItemCreateView.as_view(), name='menu_create'),
    path('menu/<int:pk>/edit/', views.ItemUpdateView.as_view(), name='menu_edit'),
    path('menu/<int:pk>/delete/', views.ItemDeleteView.as_view(), name='menu_delete'),
    path('menu_shop/comments/', views.CommentManageView.as_view(), name='comment_manage'),
    path('menu_shop/comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

reservations/models.py
import datetime
from datetime import timedelta
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.


class Items(models.Model):
    category = models.CharField(max_length=100, verbose_name="カテゴリ")
    name = models.CharField(max_length=200, verbose_name="品名")
    price = models.IntegerField(verbose_name="価格（税抜）")
    sort = models.IntegerField(verbose_name="ソート用")
    order_deadline = models.DateField(blank=True, null=True, verbose_name="注文期限")

    def __str__(self):
        return self.name


class Reservation(models.Model):
    customer_name = models.CharField(max_length=60, verbose_name="代表者名")
    phone_number = models.CharField(max_length=15, verbose_name="お電話番号（ハイフンなし）")
    hour = models.PositiveIntegerField(verbose_name="ご利用時間")
    start = models.DateTimeField(verbose_name="開始時間")
    end = models.DateTimeField(verbose_name="終了時間", null=True, blank=True)
    seat_count = models.PositiveIntegerField(verbose_name="予約席数", default=1)
    remark = models.TextField(max_length=200, verbose_name="備考欄", null=True, blank=True)
    RESERVATION_IS_PREORDER = ((1, '事前注文'), (2, 'お店で注文'))
    is_preorder = models.IntegerField(choices=RESERVATION_IS_PREORDER, verbose_name="事前注文の有無")
    RESERVATION_IS_EATIN = ((1, 'イートイン'), (2, 'テイクアウト'))
    is_eatin = models.IntegerField(choices=RESERVATION_IS_EATIN, verbose_name="イートイン/テイクアウト")
    menu_items = models.ManyToManyField(Items, through='ReservationItem', verbose_name="注文メニュー")

    def save(self, *args, **kwargs):
        if self.start and self.hour:
            self.end = self.start + timedelta(hours=self.hour)
        super().save(*args, **kwargs)


class ReservationItem(models.Model):
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE, related_name="items")
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.item.name} x {self.quantity}"


class Comment(models.Model):
    content = models.TextField(max_length=200, verbose_name="お知らせ内容")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日")

    def __str__(self):
        return self.content[:50]  # コメントの最初の50文字を表示

reservations/views.py
import datetime
import math
from django.db.models import Sum
from datetime import datetime, timedelta
from django.utils.timezone import make_aware
from typing import Any
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django.utils.timezone import now
from .models import Reservation, ReservationItem, Items, Comment
from django.views import generic
from django.conf import settings
from .forms import ReservationForm, ItemForm, ShopReservationForm, CommentForm
from django.core.exceptions import ValidationError
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UserRegistrationForm
from django.http import HttpResponseForbidden
from django.views import View
from django.db import models
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.
###################################################################################
# ここから顧客用
###################################################################################
class LoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'reservations/login.html'

    # 店舗からのお知らせ表示
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.all().order_by('-created_at')[:3]  # 最新3件を表示
        return context


class LogoutView(LogoutView):
    template_name = 'reservations/logout.html'


class MenuUserView(LoginRequiredMixin, TemplateView):
    template_name = 'reservations/menu_user.html'


class ReservationListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = 'reservations/reservation_list.html'  # 使用するテンプレート名
    context_object_name = 'reservations'  # テンプレートで使用するオブジェクト名

    def get_queryset(self):
        phone_number = self.request.GET.get('phone_number', '')  # URLクエリパラメータから電話番号を取得
        if phone_number:
            today = now().date()  # 現在の日付を取得
            return Reservation.objects.filter(
                phone_number=phone_number,
                start__date__gte=today  # 今日以降の予約を取得
            ).order_by('start')  # 予約日が近い順に並べる
        return Reservation.objects.none()  # 電話番号が渡されていない場合は空のクエリセットを返す

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['phone_number'] = self.request.GET.get('phone_number', '')
        return context


class ReservationDetailView(LoginRequiredMixin, TemplateView):
    template_name = "reservations/reservation_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation_id = kwargs.get("pk")
        reservation = get_object_or_404(Reservation, id=reservation_id)
        reservation_items = ReservationItem.objects.filter(reservation=reservation)

        # 注文メニューの詳細を計算
        reservation_details = []
        total_excl_tax = 0

        for item in reservation_items:
            item_total = item.item.price * item.quantity  # 小計
            total_excl_tax += item_total
            reservation_details.append({
                "name": item.item.name,
                "quantity": item.quantity,
                "price": item.item.price,
                "total": item_total,
            })

        tax_amount = math.floor(total_excl_tax * 0.1)  # 消費税額（切り捨て）
        discount_amount = math.floor((total_excl_tax + tax_amount) * 0.1)  # 割引額（切り捨て）
        total_incl_tax = total_excl_tax + tax_amount - discount_amount

        # コンテキストに追加
        context.update({
            "reservation": reservation,
            "reservation_details": reservation_details,
            "total_excl_tax": total_excl_tax,
            "tax_amount": tax_amount,
            "discount_amount": discount_amount,
            "total_incl_tax": total_incl_tax,
        })

        return context


class ReservationEditView(LoginRequiredMixin, UpdateView):
    model = Reservation
    form_class = ReservationForm
    template_name = 'reservations/reservation_edit.html'

    def get_object(self):
        reservation_id = self.kwargs.get('pk')
        return get_object_or_404(Reservation, id=reservation_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation = self.get_object()
        reservation_items = reservation.items.all()
        context['reservation_items'] = reservation_items
        return context

    def form_valid(self, form):
        reservation = form.save(commit=False)

        # 予約内容を保存
        reservation.save()

        # 既存の注文を削除（重複しないように）
        reservation.items.all().delete()

        # 注文メニューを保存（フォームから入力された数量を使って）
        form.save_menus(reservation)

        # 予約詳細ページへリダイレクト
        return redirect('reservation_detail', pk=reservation.id)


class ReservationDeleteView(LoginRequiredMixin, DeleteView):
    model = Reservation
    success_url = reverse_lazy('menu_user')

    def dispatch(self, request, *args, **kwargs):
        reservation = self.get_object()
        current_time = now()
        
        # 当日0時以降の場合、削除を禁止
        if reservation.start.date() == current_time.date() and current_time.hour >= 0:
            return HttpResponseForbidden('当日のご予約はキャンセルできません。')
        
        return super().dispatch(request, *args, **kwargs)


class CalendarView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'reservations/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.now().date()  # 今日の日付を取得
        max_seats = 8  # 1時間あたりの最大席数

        # 祝日を settings.py から取得
        public_holidays = settings.PUBLIC_HOLIDAYS

        # URLから年・月・日を取得し、基準日を設定
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if year and month and day:
            base_date = datetime(year=int(year), month=int(month), day=int(day)).date()
        else:
            base_date = today

        days = [base_date + timedelta(days=i) for i in range(7)]
        start_day = days[0]
        end_day = days[-1]

        calendar = {}
        for hour in range(9, 17):  # 営業時間
            row = {}
            for day in days:
                start_time = make_aware(datetime.combine(day, datetime.min.time().replace(hour=hour)))
                end_time = start_time + timedelta(hours=1)

                # 予約済み席数を計算
                reserved_seats = Reservation.objects.filter(
                    start__lt=end_time,
                    end__gt=start_time
                ).aggregate(total=Sum('seat_count'))['total'] or 0

                # 残り席数を計算
                remaining_seats = max_seats - reserved_seats
                row[day] = remaining_seats

            calendar[hour] = row

        context['public_holidays'] = public_holidays
        context['calendar'] = calendar
        context['days'] = days
        context['start_day'] = start_day
        context['end_day'] = end_day
        context['before'] = days[0] - timedelta(days=7)
        context['next'] = days[-1] + timedelta(days=1)
        context['today'] = today

        return context


class ReservationView(LoginRequiredMixin, CreateView):
    template_name = 'reservations/reservation_form.html'
    form_class = ReservationForm  # 顧客用フォームを指定
    model = Reservation

    def get_initial(self):
        initial = super().get_initial()

        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        hour = self.kwargs.get('hour')

        if year and month and day and hour:
            start_time = datetime(year=int(year), month=int(month), day=int(day), hour=int(hour))
            initial['start'] = make_aware(start_time)

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.get_form()

        items_fields = [field for field in form if field.name.startswith('item_')]
        other_fields = [field for field in form if not field.name.startswith('item_')]

        context['form'] = form
        context['items_fields'] = items_fields
        context['other_fields'] = other_fields

        form = context.get('form') 
        return context

    def form_valid(self, form):
        reservation = form.save(commit=False)
        reservation.end = reservation.start + timedelta(hours=reservation.hour)
        
        reservation.save()
        form.save_menus(reservation)

        return redirect(reverse('complete') + f'?reservation_id={reservation.id}')
    
    def form_invalid(self, form):
        # フォームエラーをコンテキストに渡す
        return self.render_to_response(self.get_context_data(form=form))


class ReservationCompleteView(LoginRequiredMixin, TemplateView):
    template_name = 'reservations/reservation_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation_id = self.request.GET.get("reservation_id")
        reservation = get_object_or_404(Reservation, id=reservation_id)
        reservation_items = ReservationItem.objects.filter(reservation=reservation)

        reservation_details = []
        total_excl_tax = 0


reservations/templates/reservations/all_reservations_list.html
{% extends 'base.html' %}

{% block title %}店舗側 全予約一覧{% endblock %}

{% block content %}
<h1>店舗側 全予約一覧</h1>

{% if reservations %}
    <table border="1" style="width: 80%;">
        <thead>
            <tr>
                <th>予約番号</th>
                <th>予約席数</th>
                <th>代表者名</th>
                <th>電話番号</th>
                <th>予約日時</th>
                <th>終了時間</th>               
                <th>事前注文</th>
                <th>イートイン/テイクアウト</th>
                <th>備考</th>
                <th>アクション</th>
            </tr>
        </thead>
        <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.seat_count }}</td>
                    <td>{{ reservation.customer_name }}</td>
                    <td>{{ reservation.phone_number }}</td>
                    <td>{{ reservation.start|date:"Y-m-d H:i" }}</td>
                    <td>{{ reservation.end|date:"H:i" }}</td>                   
                    <td>{{ reservation.get_is_preorder_display }}</td>
                    <td>{{ reservation.get_is_eatin_display }}</td>
                    <td>{{ reservation.remark }}</td>
                    <td>
                        <a href="{% url 'menu_shop_detail' pk=reservation.pk %}">詳細</a> 
                        <a href="{% url 'menu_shop_edit' pk=reservation.pk %}">編集</a> 
                        <a href="{% url 'menu_shop_delete' pk=reservation.pk %}">キャンセル</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>今日以降の予約はありません。</p>
{% endif %}
<br>
{#ページの表示#}
{{ page_obj.number }} / {{page_obj.paginator.num_pages}} ページ <br>
{# 前へ #}
{% if page_obj.has_previous %}
<a href="?page=1">&laquo; 先頭</a>
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{# 次へ #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
<a href="?page={{ page_obj.paginator.num_pages}}">最後 &raquo;</a>
{% endif %}
<br>
<br>
<a href="{% url 'menu_shop' %}">店舗用 メニュー画面に戻る</a>
{% endblock %}

reservations/templates/reservations/calendar.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}空席確認カレンダー{% endblock %}
{% block content %}
<h1>空席確認カレンダー</h1>
<p>{{ start_day }} - {{ end_day }}</p>
<table style="table-layout: fixed; width: 80%;" border="1">
    <tr>
        <td><a href="{% url 'calendar' before.year before.month before.day %}">前週</a></td>
        {% for day in days %}
            {% if day in public_holidays %}
                <th style="color: green;">{{ day | date:"d(D)" }}</th>
            {% elif day.weekday == 5 %}
                <th style="color: blue;">{{ day | date:"d(D)" }}</th>
            {% elif day.weekday == 6 %}
                <th style="color: red;">{{ day | date:"d(D)" }}</th>
            {% else %}
                <th>{{ day | date:"d(D)" }}</th>
            {% endif %}
        {% endfor %}
        <td><a href="{% url 'calendar' next.year next.month next.day %}">次週</a></td>
    </tr>

    {% for hour, schedules in calendar.items %}
        <tr>
            <td>{{ hour }}:00</td>
            {% for day, remaining_seats in schedules.items %}
                <td>
                    {% if day in public_holidays %}
                        -  <!-- 祝日は休み -->
                    {% elif day.weekday == 5 or day.weekday == 6 %}
                        -  <!-- 土日は休み -->
                    {% elif day <= today %}
                        -  <!-- 過去の枠は表示しない -->
                    {% elif remaining_seats > 0 %}
                        <a href="{% url 'reserve' day.year day.month day.day hour %}">
                            残り{{ remaining_seats }}席
                        </a>
                    {% else %}
                        満席
                    {% endif %}
                </td>
            {% endfor %}
            <td>{{ hour }}:00</td>
        </tr>
    {% endfor %}
</table>
<br>

<a href="{% url 'menu_user' %}">メニュー画面に戻る</a>
{% endblock %}

reservations/templates/reservations/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>メニュー削除確認</h1>
    <p>本当にこのメニューを削除しますか？</p>
    <p>メニュー名: {{ object.name }}</p>
    <p>価格: ¥{{ object.price }}</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">削除</button>
        <br><br>
        <a href="{% url 'menu' %}">メニュー一覧に戻る</a>
    </form>
{% endblock %}

reservations/templates/reservations/item_edit.html
{% extends 'base.html' %}

{% block title %}メニュー編集{% endblock %}

{% block content %}
    <h1>メニュー編集</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">保存</button>
    </form>
    <br>
    <a href="{% url 'menu' %}">メニュー一覧に戻る</a>
{% endblock %}

reservations/templates/reservations/item_form.html
{% extends 'base.html' %}

{% block title %}メニュー編集{% endblock %}

{% block content %}
    <h1>メニュー編集</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">保存</button>
    </form>
    <br>
    <a href="{% url 'menu' %}">メニュー一覧に戻る</a>
{% endblock %}

reservations/templates/reservations/reservation_complete.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}ご予約完了{% endblock %}
{% block content %}
<h2>ご予約完了</h2>
<p>ご予約ありがとうございます。ご来店をお待ちしております。</p>
{% if reservation %}
  <ul>
    <li><strong>予約番号:</strong> {{ reservation.id }}</li>
    <li><strong>予約席数:</strong> {{ reservation.seat_count }}</li>
    <li><strong>代表者名:</strong> {{ reservation.customer_name }}</li>
    <li><strong>電話番号:</strong> {{ reservation.phone_number }}</li>
    <li><strong>予約日時:</strong> {{ reservation.start|date:"Y-m-d H:i" }} ~ {{ reservation.end|date:"H:i" }}</li>
    <li><strong>事前注文:</strong> {{ reservation.get_is_preorder_display }}</li>
    <li><strong>イートイン/テイクアウト:</strong> {{ reservation.get_is_eatin_display }}</li>
  </ul>

  <h3>注文したメニュー</h3>
  {% if reservation_details %}
    <ul>
      {% for item in reservation_details %}
        <li>{{ item.name }} x {{ item.quantity }} (¥{{ item.total|floatformat:0|intcomma }})</li>
      {% endfor %}
    </ul>

    <!-- 金額の表示 -->
    <h4>税抜き合計金額: ¥{{ total_excl_tax|intcomma }}</h4>
    <h4>消費税額(10%): +¥{{ tax_amount|intcomma }}</h4>
    <h4 style="color: green;">10%オフクーポン適用: -¥{{ discount_amount|intcomma }}</h4>
    <h4>-------------------------</h4>
    <h4>合計金額: ¥{{ total_incl_tax|intcomma }}</h4>
    <p>お会計時にこの画面をスタッフにお見せください。</p>
    <p>ご予約時間から15分過ぎてもお越し頂けない場合はご予約をキャンセルさせていただきます。</p>
  {% else %}
    <p>注文はありません。</p>
  {% endif %}
{% else %}
  <p>予約情報が見つかりませんでした。</p>
{% endif %}

<a href="{% url 'menu_user' %}">メニュー画面に戻る</a>
{% endblock %}

reservations/templates/reservations/reservation_confirm_delete.html
{% extends 'base.html' %}

{% block title %}予約削除確認{% endblock %}

{% block content %}
<h1>予約削除確認</h1>
<p>本当にこの予約を削除しますか？</p>

<p><strong>予約番号:</strong> {{ reservation.id }}</p>
<p><strong>代表者名:</strong> {{ reservation.customer_name }}</p>
<p><strong>電話番号:</strong> {{ reservation.phone_number }}</p>
<p><strong>予約日時:</strong> {{ reservation.start|date:"Y-m-d H:i" }} ~ {{ reservation.end|date:"H:i" }}</p>

<form action="{% url 'reservation_delete' reservation.id %}" method="post">
    {% csrf_token %}
    <button type="submit">削除する</button>
</form>
<br>
<a href="{% url 'reservation_list' %}?phone_number={{ reservation.phone_number }}">予約一覧に戻る</a>

{% endblock %}

reservations/templates/reservations/shop_reservation_complete.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<h2>店舗側 予約完了</h2>

{% if reservation %}
  <ul>
    <li><strong>予約番号:</strong> {{ reservation.id }}</li>
    <li><strong>予約席数:</strong> {{ reservation.seat_count }}</li>
    <li><strong>代表者名:</strong> {{ reservation.customer_name }}</li>
    <li><strong>電話番号:</strong> {{ reservation.phone_number }}</li>
    <li><strong>予約日時:</strong> {{ reservation.start|date:"Y-m-d H:i" }} ~ {{ reservation.end|date:"H:i" }}</li>
    <li><strong>事前注文:</strong> {{ reservation.get_is_preorder_display }}</li>
    <li><strong>イートイン/テイクアウト:</strong> {{ reservation.get_is_eatin_display }}</li>
  </ul>

  <h3>注文したメニュー</h3>
  {% if reservation_details %}
    <ul>
      {% for item in reservation_details %}
        <li>{{ item.name }} x {{ item.quantity }} (¥{{ item.total|floatformat:0 }})</li>
      {% endfor %}
    </ul>

  <!-- 金額の表示 -->
  <h4>税抜き合計金額: ¥{{ total_excl_tax|intcomma }}</h4>
  <h4>消費税額(10%): +¥{{ tax_amount|intcomma }}</h4>
  <h4 style="color: green;">10%オフクーポン: -¥{{ discount_amount|intcomma }}</h4>
  <h4>-------------------------</h4>
  <h4>合計金額: ¥{{ total_incl_tax|intcomma }}</h4>
{% else %}
  <p>注文はありません。</p>
{% endif %}
{% else %}
  <p>予約情報が見つかりませんでした。</p>
{% endif %}

<a href="{% url 'menu_shop' %}">店舗用 メニュー画面に戻る</a>
{% endblock %}

reservations/templates/reservations/shop_reservation_confirm_delete.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}ご予約キャンセル確認{% endblock %}

{% block content %}
<h1>ご予約キャンセル確認</h1>
<p>本当にこの予約をキャンセルしますか？</p>

<ul>
    <li><strong>予約番号:</strong> {{ reservation.id }}</li>
    <li><strong>予約席数:</strong> {{ reservation.seat_count }}席</li>
    <li><strong>代表者名:</strong> {{ reservation.customer_name }} 様</li>
    <li><strong>電話番号:</strong> {{ reservation.phone_number }}</li>
    <li><strong>お時間:</strong> {{ reservation.start|date:"Y-m-d H:i" }} ~ {{ reservation.end|date:"H:i" }}</li>
    <li><strong>備考:</strong> {{ reservation.remark }}</li>
    <li><strong>事前注文:</strong> {{ reservation.get_is_preorder_display }}</li>
    <li><strong>イートイン/テイクアウト:</strong> {{ reservation.get_is_eatin_display }}</li>
</ul>

<form action="{% url 'menu_shop_delete' reservation.id %}" method="post">
    {% csrf_token %}
    <button type="submit">キャンセルする</button>
</form>
<br>
<a href="{% url 'menu_shop_list' %}">店舗側 全予約一覧に戻る</a>

{% endblock %}

reservations/templates/reservations/shop_reservation_detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load humanize %}
{% block title %}ご予約詳細{% endblock %}

{% block content %}
<h1>ご予約詳細</h1>

<h3>ご予約情報</h3>
<ul>
  <li><strong>予約番号:</strong> {{ reservation.id }}</li>
  <li><strong>予約席数:</strong> {{ reservation.seat_count }}席</li>
  <li><strong>代表者名:</strong> {{ reservation.customer_name }} 様</li>
  <li><strong>電話番号:</strong> {{ reservation.phone_number }}</li>
  <li><strong>お時間:</strong> {{ reservation.start|date:"Y-m-d H:i" }} ~ {{ reservation.end|date:"H:i" }}</li>
  <li><strong>備考:</strong> {{ reservation.remark }}</li>
  <li><strong>事前注文:</strong> {{ reservation.get_is_preorder_display }}</li>
  <li><strong>イートイン/テイクアウト:</strong> {{ reservation.get_is_eatin_display }}</li>
</ul>

<h3>注文したメニュー</h3>
{% if reservation_details %}
  <ul>
    {% for item in reservation_details %}
      <li>{{ item.name }} x {{ item.quantity }} (¥{{ item.total|intcomma }})</li>
    {% endfor %}
  </ul>

  <!-- 金額の表示 -->
  <h4>税抜き合計金額: ¥{{ total_excl_tax|intcomma }}</h4>
  <h4>消費税額(10%): +¥{{ tax_amount|intcomma }}</h4>
  <h4 style="color: green;">10%オフクーポン: -¥{{ discount_amount|intcomma }}</h4>
  <h4>-------------------------</h4>
  <h4>合計金額: ¥{{ total_incl_tax|intcomma }}</h4>
{% else %}
  <p>注文はありません。</p>
{% endif %}
<br>
<a href="{% url 'menu_shop_list' %}">店舗側 全予約一覧に戻る</a>
{% endblock %}